version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: '/derive'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: '/qtok'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
