[package]
name = "rqjs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.104"
libquickjs-sys = { version = "0.10.0", features = ["patched"] }
